dist: xenial
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - "echo '<settings><localRepository>${env.HOME}/.m2/repository</localRepository><servers><server><id>sonatype-nexus-snapshots</id><username>${env.CI_DEPLOY_USERNAME}</username><password>${env.CI_DEPLOY_PASSWORD}</password></server></servers></settings>' > $HOME/settings.xml"
  - "[[ $TRAVIS_PULL_REQUEST == 'false' ]] && export MAVEN_PHASE=deploy || export MAVEN_PHASE=install"

jobs:
  include:
    - os: linux
      arch: arm64
      language: java
      addons:
        apt:
          packages: openjdk-8-jdk openjfx maven
      env: PLATFORMS="linux-arm64"
      install:
        - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
      script:
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml -f platform/pom.xml -Djavacpp.platform=linux-arm64
    - os: linux
      arch: ppc64le
      language: java
      addons:
        apt:
          packages: openjdk-8-jdk openjfx maven
      env: PLATFORMS="linux-ppc64le"
      install:
        - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-ppc64el"
      script:
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml -f platform/pom.xml -Djavacpp.platform=linux-ppc64le
    - os: linux
      arch: amd64
      language: java
      addons:
        apt:
          packages: openjdk-8-jdk openjfx maven
      env: PLATFORMS="linux-x86_64"
      install:
        - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      script:
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml -f platform/pom.xml -Djavacpp.platform=linux-x86_64
    - os: osx
      osx_image: xcode12.2
      language: java
      env: PLATFORMS="macosx-x86_64"
      install:
        - brew update
        - brew install gpg1
        - brew tap AdoptOpenJDK/openjdk
        - brew install --cask adoptopenjdk8
        - export JAVA_HOME=$(/usr/libexec/java_home -v1.8)
      script:
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml
        - mvn clean $MAVEN_PHASE -B -V -U -s $HOME/settings.xml -f platform/pom.xml -Djavacpp.platform=macosx-x86_64 '-Dtest=!FrameGrabberTest,!FrameGrabberChangingResolutionTest'
    - os: windows
      language: bash
      env: PLATFORMS="windows-x86_64"
      install:
        - powershell Install-WindowsFeature Server-Media-Foundation
        - choco install jdk8 --params 'installdir=c:\\jdk8'
        - choco install maven --version=3.6.3
        - export JAVA_HOME="/c/jdk8/"
        - export PATH="$PATH:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin/:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/"
      script:
        - cmd.exe //C 'vcvarsall.bat amd64 && mvn clean %MAVEN_PHASE% -B -V -U -s %HOME%/settings.xml'
        - cmd.exe //C 'vcvarsall.bat amd64 && mvn clean %MAVEN_PHASE% -B -V -U -s %HOME%/settings.xml -f platform/pom.xml -Djavacpp.platform=windows-x86_64 -Dtest=!FrameConverterTest#testOpenCV*'
