name: javacv
on: [push, pull_request, workflow_dispatch]
env:
  CI_DEPLOY_MODULE: .
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          sudo: false
  macosx-arm64:
    runs-on: macos-15
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
  macosx-x86_64:
    runs-on: macos-15-intel
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
  windows-x86_64:
    runs-on: windows-2022
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
  platform:
    needs: [linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
